EHI-49: Implemented Stack & Queue
EduHubICT/python-basic pull request #10
Opened 2020-06-13 11:19 UTC by imShakil

2020-06-13 11:55 UTC, jonyroy reviewed
create test for each and every function separately

2020-06-13 14:48 UTC, imShakil commented
please, have a look. I have updated stack & queue as you said.

2020-06-13 16:35 UTC, jonyroy requested changes

2020-06-13 16:35 UTC, jonyroy commented on src/main/data_structure/queue.py
> +            return "An empty Queue."
raise an exception instead of returning An empty Queue
https://www.w3schools.com/python/gloss_python_raise.asp#:~:text=Raise%20an%20exception,exception%2C%20use%20the%20raise%20keyword.

2020-06-13 16:35 UTC, jonyroy commented on src/main/data_structure/queue.py
> +            return "An empty Queue."
raise an exception instead of returning An empty Queue
https://www.w3schools.com/python/gloss_python_raise.asp#:~:text=Raise%20an%20exception,exception%2C%20use%20the%20raise%20keyword

2020-06-13 16:35 UTC, jonyroy commented on src/main/data_structure/stack.py
> +            print("An empty stack")
raise an exception instead of printing An empty Queue
https://www.w3schools.com/python/gloss_python_raise.asp#:~:text=Raise%20an%20exception,exception%2C%20use%20the%20raise%20keyword

2020-06-13 16:35 UTC, jonyroy commented on src/main/data_structure/stack.py
> +            print("An empty stack")
raise an exception instead of printing An empty Queue
https://www.w3schools.com/python/gloss_python_raise.asp#:~:text=Raise%20an%20exception,exception%2C%20use%20the%20raise%20keyword

2020-06-14 01:28 UTC, imShakil commented on src/main/data_structure/stack.py
> +            print("An empty stack")
okay, let me try.

2020-06-14 12:04 UTC, jonyroy requested changes

2020-06-14 12:04 UTC, jonyroy commented on src/main/data_structure/queue.py
> +    def pop(self):
prev code was okay. we just need to throw an exception like

raise Exception('You are trying to pop an empty Queue')
we don't need try catch here

2020-06-14 12:04 UTC, jonyroy commented on src/main/data_structure/stack.py
> +    def top(self):
prev code was okay. we just need to throw an exception like

raise Exception('You are trying to top an empty Stack')
we don't need try catch here

2020-06-14 12:04 UTC, jonyroy commented on src/main/data_structure/stack.py
> +    def pop(self):
prev code was okay. we just need to throw an exception like

raise Exception('You are trying to pop an empty Stack')
we don't need try catch here

2020-06-14 12:04 UTC, jonyroy commented on src/main/data_structure/tuple_exercise.py
> +        tuple2 = self.tuple[index+1:tuple_length]
place spaces

2020-06-14 12:04 UTC, jonyroy commented on src/main/data_structure/tuple_exercise.py
> +        return tuple1+tuple2
place spaces

2020-06-14 12:04 UTC, jonyroy commented on src/main/data_structure/tuple_exercise.py
> +        return self.tuple*times
place spaces

2020-06-14 15:52 UTC, jonyroy approved these changes
LGTM

2020-06-14 15:53 UTC, merged