[EHI-53] Added insertion sort
EduHubICT/python-basic pull request #14
Opened 2020-06-15 02:22 UTC by Ahad726

2020-06-15 16:45 UTC, jonyroy requested changes

2020-06-15 16:45 UTC, jonyroy commented on src/main/data_structure/list_exercise.py
> +
remove the unnecessary new lines

2020-06-16 10:50 UTC, Ahad726 commented on src/main/data_structure/list_exercise.py
> +
Thank you, I will remove those lines.

2020-06-16 14:17 UTC, jonyroy approved these changes
LGTM

2020-06-16 14:17 UTC, merged