[EHI - 50] Function to find all elements greater than all elements to its right
EduHubICT/python-basic pull request #18
Opened 2020-06-23 05:18 UTC by RijviZ

2020-06-24 10:25 UTC, jonyroy requested changes

2020-06-24 10:25 UTC, jonyroy commented on src/main/data_structure/stack.py
> +    # Function to find all elements which are greater than all elements present to its right
implement this with List instead of Stack

2020-06-24 17:32 UTC, imShakil commented on src/main/data_structure/list_exercise.py
> +
we can remove this space

2020-06-24 17:32 UTC, imShakil commented on src/main/data_structure/list_exercise.py
> +
we can remove this space

2020-06-24 17:32 UTC, imShakil commented on src/main/data_structure/list_exercise.py
> +
We can remove this space

2020-06-25 07:57 UTC, RijviZ commented on src/main/data_structure/list_exercise.py
> +
I did not solve this.
This is not mine

2020-06-28 10:13 UTC, jonyroy approved these changes

2020-06-28 10:14 UTC, merged